# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
field_selection:
  transaction_fields:
    - hash
networks:
  - id: 69
    start_block: 24383866
    rpc_config:
      url: https://minanet-fork-production.up.railway.app
    contracts:
      - name: Launchpad
        address:
          - 0x63e39e1b03a72B721D6398D67A646705B33979eD
        handler: src/EventHandlers.ts
        events:
          - event: TokenLaunched(address indexed token, address indexed strategy, address indexed auction, address creator, string name, string symbol, string description, string website, string image, uint64 auctionStartBlock, uint64 auctionEndBlock, uint64 auctionClaimBlock, uint64 poolMigrationBlock, bytes32 salt)
unordered_multichain_mode: true
preload_handlers: true
